---
- name: install nginx
  apt: pkg=nginx-light state=present

- name: remove dist servers
  file: "dest=/etc/nginx/sites-{{ item[0] }}/{{ item[1] }} state=absent"
  with_nested:
    - ["enabled", "available"]
    - ["default"]

- name: create www directory
  file: "path={{ nginx_www_dir }} state=directory owner={{ nginx_user }} group={{ nginx_group }} mode=0755"

- name: write default server
  template: "src=default.conf dest=/etc/nginx/sites-available/default.conf owner=root group=root mode=0644"
  when: nginx_set_default_server
  notify: reload nginx

- name: activate default server
  file: "src=/etc/nginx/sites-available/default.conf dest=/etc/nginx/sites-enabled/default.conf state=link"
  when: nginx_set_default_server
  notify: reload nginx

- name: Write Nginx monitor
  template: src=monitors/{{ item }}.j2 dest=/etc/monit/conf.d/{{ item }} owner=root group=root
  with_items: monit_services
  notify: restart monit
  tags: nginx
